#!/bin/bash
# Automate the process of making API requests to the Pokémon API and saving the results to a file

handle_error() {
    echo "An error occurred. Exiting..." >> errors.txt
    exit 1
}

trap handle_error ERR

curl -o data.json  https://pokeapi.co/api/v2/pokemon/

