#!/bin/bash
# Speed up data retrieval using parallel processing.

handle_error() {
    echo "An error occurred. Exiting..." >> errors.txt
    exit 1
}

trap handle_error ERR

pokemons=(bulbasaur ivysaur venusaur charmander charmeleon)

api=$(curl https://pokeapi.co/api/v2/pokemon/)

api_list=$(echo $api | jq -c '.results')

mkdir -p pokemon_data

fetch_pokemon() {
	local name="$1"
	echo "Fetching data for ${name}..."
	select_api=$(echo $api_list | jq -r --arg named "$name" '.[] | select(.name==$named) | .url')
	if [ -n "$select_api" ];then
		curl -s -o pokemon_data/${name}.json "$select_api"
		echo "Saved data to pokemon_data/${name}.json ✅"
	fi
}

PIDS=()

for pokemon in "${pokemons[@]}"; do
    fetch_pokemon "$pokemon" &
    PIDS+=($!)
done

for pid in "${PIDS[@]}"; do
    wait "$pid"
    if [ $? -ne 0 ]; then
        echo "Process $pid for a Pokémon fetch failed."
    fi
done

echo "All Pokemon data processes completed."
