#!/bin/bash
# Create a report that summarizes data for multiple Pokémon.

handle_error() {
    echo "An error occurred. Exiting..." >> errors.txt
    exit 1
}

trap handle_error ERR

total_height=0
total_weight=0
count=0

echo "CSV Report generated at: pokemon_report.csv" > "pokemon_report.csv"
echo "" >> "pokemon_report.csv"
echo "Name,Height (m),Weight (kg)" >> "pokemon_report.csv"

for json_file in pokemon_data/*.json; do
        name=$(jq -r '.forms.[0].name' "$json_file")
        weight=$(jq -r '.weight' "$json_file")
        height=$(jq -r '.height' "$json_file")

        f_height=$(awk "BEGIN { printf \"%.1f\", $height / 10 }")
        f_weight=$(awk "BEGIN { printf \"%.0f\", $weight / 10 }")

	echo "$name,$f_height,$f_weight" >> "pokemon_report.csv"
	
	total_height=$(awk "BEGIN { print $total_height + $f_height }")
  	total_weight=$(awk "BEGIN { print $total_weight + $f_weight }")
  	count=$((count + 1))
done

average_height=$(awk "BEGIN { printf \"%.2f\", $total_height / $count }")
average_weight=$(awk "BEGIN { printf \"%.2f\", $total_weight / $count }")

echo "" >> "pokemon_report.csv"
echo "Average Height: $average_height m" >> "pokemon_report.csv"
echo "Average Weight: $average_weight kg" >> "pokemon_report.csv"

cat pokemon_report.csv
